AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM template Administratum Discord bot'

# standard Lambda settings
Globals:
  Function:
    Timeout: 900
    MemorySize: 128
    Runtime: python3.9
# define environment variables
Parameters:
  GLOBALS3BUCKET:
    Type: "String"
    Default: "administratum-test"
    Description: Enter the name of the S3 bucket to use
  GLOBALSECRETARN:
    Type: "String"
    Default: "arn:aws:secretsmanager:eu-west-1:12345:secret:discord-administratum"
    Description: ARN the name of the secret in Secret Manager
  GLOBALREGION:
    Type: "String"
    Default: "eu-west-1"
    Description: Enter the name of the region the entry in secret manager is deployed to




Resources:

  # S3 resource setup (bucket and policy)
  S3ResourceStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: GLOBALS3BUCKET
  S3ResourcePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: GLOBALS3BUCKET
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3ResourceStorage, "/Resources/*" ] ]
            Principal: '*'
          - Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3ResourceStorage ] ]
            Principal: '*'

# The API gateway setup that Discord will talk to
  AdministratumAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test

# Lambda setup sections
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that authenticates (or rejects) the message sent from Discord
      Handler: Lambda_Function.lambda_handler
      CodeUri: Lambda/AuthFunction/
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: GetWebhookFunction
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: GLOBALSECRETARN
      Layers:
        - !Ref PyNaClLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /Administratum
            Method: post
            RestApiId: !Ref AdministratumAPIGateway
      Environment:
        Variables:
          SECRET_ARN:
            Ref: GLOBALSECRETARN
          REGION:
            Ref: GLOBALREGION
          NEXT_LAMBDA:
            Ref: GetWebhookFunction

  PyNaClLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: PyNaCL layer to allow verification of the signature supplied by Discord
      CompatibleRuntimes:
        - python3.8
      ContentUri: Lambda/AuthFunction/Layers/pynacl-layer.zip
      LayerName: pynacl
      RetentionPolicy: Retain

  GetWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that identifies the appropriate webhook URL for the message
      Handler: Lambda_Function.lambda_handler
      CodeUri: Lambda/GetWebhookFunction/
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: SendWebhookFunction
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref:  GLOBALSECRETARN

      Environment:
        Variables:
          NEXT_LAMBDA:
            Ref: SendWebhookFunction
          SECRET_ARN:
            Ref: GLOBALSECRETARN
          REGION:
            Ref: GLOBALREGION

  SendWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that sends the requested webhook to the channel
      Handler: Lambda_Function.lambda_handler
      CodeUri: Lambda/SendWebhookFunction/
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: GLOBALSECRETARN
      Environment:
        Variables:
          SECRET_ARN:
            Ref: GLOBALSECRETARN
          REGION:
            Ref: GLOBALREGION

  RegisterResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that registers slash commands based on the S3 bucket's Resources directory
      Handler: populate_commands.lambda_handler
      CodeUri: Lambda/ResourcesFunction/
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: GLOBALSECRETARN
      Environment:
        Variables:
          SECRET_ARN:
            Ref: GLOBALSECRETARN
          REGION:
            Ref: GLOBALREGION

